//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortLog.RefServPortLog {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoProducto", Namespace="http://schemas.datacontract.org/2004/07/WCFProductos")]
    [System.SerializableAttribute()]
    public partial class DtoProducto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Peso {
            get {
                return this.PesoField;
            }
            set {
                if ((this.PesoField.Equals(value) != true)) {
                    this.PesoField = value;
                    this.RaisePropertyChanged("Peso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rut {
            get {
                return this.RutField;
            }
            set {
                if ((object.ReferenceEquals(this.RutField, value) != true)) {
                    this.RutField = value;
                    this.RaisePropertyChanged("Rut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Stock {
            get {
                return this.StockField;
            }
            set {
                if ((this.StockField.Equals(value) != true)) {
                    this.StockField = value;
                    this.RaisePropertyChanged("Stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod {
            get {
                return this.codField;
            }
            set {
                if ((this.codField.Equals(value) != true)) {
                    this.codField = value;
                    this.RaisePropertyChanged("cod");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoImportacion", Namespace="http://schemas.datacontract.org/2004/07/WCFProductos")]
    [System.SerializableAttribute()]
    public partial class DtoImportacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntregadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaIngresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaSalidaPrevistaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PortLog.RefServPortLog.DtoProducto ProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int precioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cod {
            get {
                return this.CodField;
            }
            set {
                if ((this.CodField.Equals(value) != true)) {
                    this.CodField = value;
                    this.RaisePropertyChanged("Cod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Entregado {
            get {
                return this.EntregadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EntregadoField, value) != true)) {
                    this.EntregadoField = value;
                    this.RaisePropertyChanged("Entregado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaIngreso {
            get {
                return this.FechaIngresoField;
            }
            set {
                if ((this.FechaIngresoField.Equals(value) != true)) {
                    this.FechaIngresoField = value;
                    this.RaisePropertyChanged("FechaIngreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaSalidaPrevista {
            get {
                return this.FechaSalidaPrevistaField;
            }
            set {
                if ((this.FechaSalidaPrevistaField.Equals(value) != true)) {
                    this.FechaSalidaPrevistaField = value;
                    this.RaisePropertyChanged("FechaSalidaPrevista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PortLog.RefServPortLog.DtoProducto Producto {
            get {
                return this.ProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductoField, value) != true)) {
                    this.ProductoField = value;
                    this.RaisePropertyChanged("Producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int precio {
            get {
                return this.precioField;
            }
            set {
                if ((this.precioField.Equals(value) != true)) {
                    this.precioField = value;
                    this.RaisePropertyChanged("precio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RefServPortLog.IServicioPortLog")]
    public interface IServicioPortLog {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPortLog/ProductoXId", ReplyAction="http://tempuri.org/IServicioPortLog/ProductoXIdResponse")]
        PortLog.RefServPortLog.DtoProducto ProductoXId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPortLog/ProductoXId", ReplyAction="http://tempuri.org/IServicioPortLog/ProductoXIdResponse")]
        System.Threading.Tasks.Task<PortLog.RefServPortLog.DtoProducto> ProductoXIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPortLog/AgregarImportacion", ReplyAction="http://tempuri.org/IServicioPortLog/AgregarImportacionResponse")]
        bool AgregarImportacion(PortLog.RefServPortLog.DtoImportacion DtoImp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPortLog/AgregarImportacion", ReplyAction="http://tempuri.org/IServicioPortLog/AgregarImportacionResponse")]
        System.Threading.Tasks.Task<bool> AgregarImportacionAsync(PortLog.RefServPortLog.DtoImportacion DtoImp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPortLog/MostrarProductos", ReplyAction="http://tempuri.org/IServicioPortLog/MostrarProductosResponse")]
        PortLog.RefServPortLog.DtoProducto[] MostrarProductos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPortLog/MostrarProductos", ReplyAction="http://tempuri.org/IServicioPortLog/MostrarProductosResponse")]
        System.Threading.Tasks.Task<PortLog.RefServPortLog.DtoProducto[]> MostrarProductosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioPortLogChannel : PortLog.RefServPortLog.IServicioPortLog, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioPortLogClient : System.ServiceModel.ClientBase<PortLog.RefServPortLog.IServicioPortLog>, PortLog.RefServPortLog.IServicioPortLog {
        
        public ServicioPortLogClient() {
        }
        
        public ServicioPortLogClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioPortLogClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPortLogClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPortLogClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PortLog.RefServPortLog.DtoProducto ProductoXId(int id) {
            return base.Channel.ProductoXId(id);
        }
        
        public System.Threading.Tasks.Task<PortLog.RefServPortLog.DtoProducto> ProductoXIdAsync(int id) {
            return base.Channel.ProductoXIdAsync(id);
        }
        
        public bool AgregarImportacion(PortLog.RefServPortLog.DtoImportacion DtoImp) {
            return base.Channel.AgregarImportacion(DtoImp);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarImportacionAsync(PortLog.RefServPortLog.DtoImportacion DtoImp) {
            return base.Channel.AgregarImportacionAsync(DtoImp);
        }
        
        public PortLog.RefServPortLog.DtoProducto[] MostrarProductos() {
            return base.Channel.MostrarProductos();
        }
        
        public System.Threading.Tasks.Task<PortLog.RefServPortLog.DtoProducto[]> MostrarProductosAsync() {
            return base.Channel.MostrarProductosAsync();
        }
    }
}
